services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:d01b7fd0af1decf19769e8b334a0c4d47995f6907402130bf49229393bbf74ba
      repository: armory/clouddriver-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:273e796db3b91b2560eda344adeb73fda321ce3e6545644f600949a11efe6663
      repository: armory/deck-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  dinghy:
    baseService: dinghy
    image:
      imageId: sha256:c4ed7b3971df71c6f1f68d1bc2f3b419fc68aaa2ecf7ee9412958ee5efb305f8
      repository: armory/dinghy
      tag: 2026.07.08.15.43.20.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: f22d5925ee1d282a725a5926317f40ff76b1d742
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:e308617c46bacd0a9ec4b39213812d46480582884248713ab28d0a0d3a846784
      repository: armory/echo-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:40ee6bfc06a64fb1e024cc8e5b410a6c258595dfb5c84f7c7667efcb2285e9d8
      repository: armory/fiat-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:d3a472aea112917322cd6bd41ba27fdfbfcb1437b64ac28747695802ed9eea1c
      repository: armory/front50-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:9dbae9adee6d5079581eb54df9f8f84e56b82c59061781c73165fab03683538a
      repository: armory/gate-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:e5eaf4cedd10aa6ebfb96f4069ea84d0090b911dfa2184dbc406e4ac1d369370
      repository: armory/igor-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:0a2b30796c33cc5a7e4f4248b58a0635d253f573294538dd43dc854d8ae0505d
      repository: armory/kayenta-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:7163438fb329a561f450fbc89419ad195a76c6b1fbfdd687e6d67896546926c6
      repository: armory/orca-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:5a2df3dceb38c060ffec6920f780577c2fde67dc4c2e3f9a994c1c9b4429b9ca
      repository: armory/rosco-armory
      tag: 2026.09.08.14.49.36.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 1cd5040f84ec4234d44eeb66371fcdc4b674712e
  terraformer:
    baseService: terraformer
    image:
      imageId: sha256:3ce8e96a8dd0c8f205fbe30fe675c6c8bddb10f65cde6206a04f65b070109e0e
      repository: armory/terraformer
      tag: 2026.07.28.14.24.20.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 789d7eaeb20ddd2544efad606ce885ff1424d34d
