services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:b8007ce81aac6393c8a3fabaac9485a3f9d3a11b77bc9e0720ce650a1ebb0072
      repository: armory/clouddriver-armory
      tag: 2026.07.14.12.17.22.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 35532b4a79ae36d7fcc48f8fadd75f0cc104d9a9
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:bcd194732ee9f05612357f895470aaec84b349cb0093cf865080ea76fcf06e77
      repository: armory/deck-armory
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  dinghy:
    baseService: dinghy
    image:
      imageId: sha256:7c4825ae0f8755abf58c63f4fc7fbe42b3b59d1d52d02dfad23976e44d309125
      repository: armory/dinghy
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:c649d8c1ba0ddc64be1e5dc6261eb8db4805605c95cb3a1bc667e0d24918dd0a
      repository: armory/echo-armory
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:769241a314ea65651e47233038fbce99c945d11b52503680d695b0dfd863631a
      repository: armory/fiat-armory
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:05cf2f53303cae157def1404c32ee16e57dbaf36f30e582294139ee77cd1234f
      repository: armory/front50-armory
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:dcd8a892013004b4f9f7eb6cda8d9e2c0715f25f5572fde47e63c3a1dd137dff
      repository: armory/gate-armory
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:5836935fd261ca56f0ad33b40f6f2366454e9e4dde1d95fd08bb8d498e78f14f
      repository: armory/igor-armory
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:8ba1a71356e48b363ef522a94bdedc7eb68ff4b91570c410beeb5eef65acad3d
      repository: armory/kayenta-armory
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:537b4077806544788974315a3db3c0906e95d0a24f5544a4dd8f792f85aabf16
      repository: armory/orca-armory
      tag: 2026.07.13.08.57.58.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: 5316cdf53a2c78f78c116ff478012d58f9974e27
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:6f114aafe48bb4c4591dc6a7b3ff766af90dd1f77c4acb44378f97ae77d2dd10
      repository: armory/rosco-armory
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
  terraformer:
    baseService: terraformer
    image:
      imageId: sha256:b377e6267bdf174a9905171bf6c05ed07e4c86cc48ccc0f59e7282bdf2e7d61f
      repository: armory/terraformer
      tag: 2026.07.15.08.54.01.release-2.40.x
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: e099cb401ee08c956cd23ff1871e2d403263f479
