services:
  clouddriver-armory:
    baseService: clouddriver
    image:
      imageId: sha256:61dc021530d450916673e22b5681fa8ac962de0abb351dcb3b76aa76ec0db263
      repository: armory/clouddriver-armory
      tag: 2026.07.07.14.13.56.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: a43a45690405c373e1a31af9c5f84c552f56a185
  deck-armory:
    baseService: deck
    image:
      imageId: sha256:591bad2b5947841af6dcdd739e4f9cb354412919b943f91802f1489bea7fe62f
      repository: armory/deck-armory
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  dinghy:
    baseService: dinghy
    image:
      imageId: sha256:57780e0643543a2b4657e3464788019e3a42edf6b394fa1c55a2754f19c35798
      repository: armory/dinghy
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  echo-armory:
    baseService: echo
    image:
      imageId: sha256:948a94bb584d625d3d7853b3e13af6026d0b44d3f02cfa9808a44dd2db07c62e
      repository: armory/echo-armory
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  fiat-armory:
    baseService: fiat
    image:
      imageId: sha256:60f89bdb55af72d4e5b808c0e5a10a803991d697ddeb3676209d6a2e3d0c6426
      repository: armory/fiat-armory
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  front50-armory:
    baseService: front50
    image:
      imageId: sha256:dda9c3c607f0d0488b328342345bc9be5624ad8186807deb93e620b188465d10
      repository: armory/front50-armory
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  gate-armory:
    baseService: gate
    image:
      imageId: sha256:9f66becbdeab51e2acfa06b50fdea21c67e0a8ba9652622ad875be9c30b8ae9a
      repository: armory/gate-armory
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  igor-armory:
    baseService: igor
    image:
      imageId: sha256:b6cdfa90b5dcbfad0b2f2cedb0e111cdcabb3517595008a357e2f8c738c425e2
      repository: armory/igor-armory
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  kayenta-armory:
    baseService: kayenta
    image:
      imageId: sha256:d4bfc203e80a76ced9282754d58b9bbdb104a7bda9c82e17ace1a0f69ca34cbb
      repository: armory/kayenta-armory
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  orca-armory:
    baseService: orca
    image:
      imageId: sha256:304a9dd2a6733298e2c73e3569be66e6d265b559e7d8ac4600506a009bcfa1f4
      repository: armory/orca-armory
      tag: 2026.07.07.13.12.00.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: d41e2819566fe58a399e4e11c49a094a401d6dc8
  rosco-armory:
    baseService: rosco
    image:
      imageId: sha256:6239ef31eae23c54e23e8ca6f11a86889dff234ad4fca5366e976ff46e7f07de
      repository: armory/rosco-armory
      tag: 2026.07.01.09.43.16.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: b7e12e1b63614ed2f679afb52806e834663784b2
  terraformer:
    baseService: terraformer
    image:
      imageId: sha256:e079006d64776ff993882463fd1950a1281647995d3bc30aed2c1d532e3621b8
      repository: armory/terraformer
      tag: 2025.08.20.02.33.17.main
    vcs:
      repo:
        orgName: armory-io
        repoName: armory-extensions
        type: github
      sha: babaa4704f1df8a6f6b42e533716396c8a0f529b
