name: Rebase Pull Requests
on:
  push:
    branches:
      - master
      - 'release-**.x'
    paths:
      - 'stack.yml'
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase Pull Requests Out Of Date
        uses: peter-evans/rebase@v4
        with:
          token: ${{ secrets.ASTROLABE_GITHUB_TOKEN }}
